language: python
sudo: required
services:
- docker
script:
- make docker/build
before_install:
- pip install codecov
after_success:
- codecov
deploy:
  provider: pypi
  user: kpn-digital
  password:
    secure: AAxcS3RxV+SCHus38cZqB08F9zpuyMoCp+P9TBmCpHslpCk5ctrMjIwjcrWhDym0oNlUF63J9TMOd4fEvn4HrhYWLoqGxRKsM0s6/JbHPOP/Vzi8FroPoJ1VFE73fLkiVEtpgz2nPSrh1nbUCtuPCxxo6rbjWf40LZjveFoKrsK/wXaU46V33OZrrgxTsIdJQ5S1a0uFg09ZE4/9ILIYVgo86pxilqqyOclYDnqvGK94+gJxHOC9AwApbA/OFx8kZRrCWlMrsKaZPvFn9l1ILDgSN+Uhx3WtHWSNTzPExjyLWbiY6WEeooZvlQhTLo6kZ2xnTrv9CcTdZZGLDr29jfba/bQdlWwCt6kqoTHTM6wZ0LauBUILP5X2gRJ+E322VccfSt+k3PRm7hup+xbanQ+/smi32ZwqQLx8X8gXYP3hOE/d1uIZsl4HS7ARPqP+zmVg3bAoWSlhg5o8MSi/gsvVUBs18EZYZHz29HhUnhATcxPklKEPuxudzDAxdgNoqaHAN4p+kQx3HF2Wvz2wGXQ8QHAn8nKXniyY3X8zY6UdSdVWXIdR3ZPJ23qudytCqEsKfZuV0rd1LrPPqS+3cutyc+hqfAtjFoDkhGW9UGaX6UfF7hXxlMvl5HYZLQheNCdwLJ3Wt2hWHtO+okH0E9lO9KBunuFzEMkzr2m952s=
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
